/**
 * Schedule poller.
 *
 * Every 5 minutes per org we call /api/whatsapp/due-posts, receive a list
 * of instructions, and execute each one. The server decides timing,
 * content, and idempotency — this code just dispatches.
 *
 * After every successful action we POST to /api/whatsapp/ack so the server
 * writes a SentNotification row and the same instruction doesn't fire again.
 */
import pkg from "whatsapp-web.js";
import { getDuePosts, ackInstruction, type DueInstruction } from "./api.js";
import { config } from "./config.js";

const { Poll } = pkg;

type Client = InstanceType<typeof pkg.Client>;

interface Org {
  groupId: string;
  orgName: string;
}

let client: Client | null = null;
let orgs: Org[] = [];
let intervalId: ReturnType<typeof setInterval> | null = null;

export function initScheduler(waClient: Client, orgConfigs: Org[]) {
  client = waClient;
  orgs = orgConfigs;

  // Poll every 5 minutes. Server handles the timing precision.
  const intervalMs = (config.schedulerIntervalMinutes ?? 5) * 60 * 1000;
  intervalId = setInterval(tick, intervalMs);
  // Kick off immediately so startup picks up any overdue instructions.
  tick().catch((err) => console.error("Initial scheduler tick failed:", err));

  console.log(
    `Scheduler started: polling due-posts every ${config.schedulerIntervalMinutes ?? 5}min for ${orgs.length} org(s)`,
  );
}

export function stopScheduler() {
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }
}

async function tick(): Promise<void> {
  if (!client) return;
  for (const org of orgs) {
    try {
      const result = await getDuePosts(org.groupId);
      if (!result || result.instructions.length === 0) continue;
      console.log(`[${org.orgName}] ${result.instructions.length} due instruction(s)`);
      for (const instr of result.instructions) {
        await executeInstruction(instr, org.groupId);
      }
    } catch (err) {
      console.error(`[${org.orgName}] scheduler tick failed:`, err);
    }
  }
}

async function executeInstruction(instr: DueInstruction, groupId: string): Promise<void> {
  if (!client) return;

  try {
    if (instr.kind === "group-message") {
      const msg = await client.sendMessage(groupId, instr.text);
      await ackInstruction({
        key: instr.key,
        kind: instr.kind,
        matchId: instr.matchId,
        waMessageId: msg.id?._serialized,
      });
      return;
    }

    if (instr.kind === "group-poll") {
      // Poll options require a messageSecret per whatsapp-web.js types; it's
      // auto-generated by the lib when omitted, but TS insists.
      // Cast to the looser type the runtime actually accepts.
      const poll = new Poll(
        instr.question,
        instr.options,
        { allowMultipleAnswers: instr.multi ?? false } as ConstructorParameters<typeof Poll>[2],
      );
      const msg = await client.sendMessage(groupId, poll);
      await ackInstruction({
        key: instr.key,
        kind: instr.kind,
        matchId: instr.matchId,
        waMessageId: msg.id?._serialized,
      });
      return;
    }

    if (instr.kind === "dm") {
      const jid = `${instr.phone}@c.us`;
      const msg = await client.sendMessage(jid, instr.text);
      await ackInstruction({
        key: instr.key,
        kind: instr.kind,
        matchId: instr.matchId,
        targetUser: instr.targetUser,
        waMessageId: msg.id?._serialized,
      });
      return;
    }

    if (instr.kind === "bench-prompt") {
      // Post in the group (@mention the user via their JID).
      const mentions = [`${instr.phone}@c.us`];
      const msg = await client.sendMessage(groupId, instr.text, { mentions });
      await ackInstruction({
        key: instr.key,
        kind: instr.kind,
        matchId: instr.matchId,
        benchUserId: instr.userId,
        waMessageId: msg.id?._serialized,
      });
      return;
    }
  } catch (err) {
    console.error(`Failed to execute instruction ${instr.kind} (${instr.key}):`, err);
  }
}
